apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-service
  labels:
    app: articles-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles-service
  template:
    metadata:
      labels:
        app: articles-service
    spec:
      containers:
        - name: articles-service
          image: anurag2911/articles-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: NATS_URL
            - name: Wiki__RefreshIntervalMinutes
              value: "1"
            - name: Wiki__BatchSize
              value: "200"
            - name: Wiki__RateLimitDelayMs
              value: "10"
            - name: Wiki__MaxRetries
              value: "3"
            - name: Wiki__RetryDelayMs
              value: "1000"
            - name: Wiki__UserAgent
              value: "articlessvc/2.0 (contact@example.com)"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /articles-api/stats
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /articles-api/stats
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
              
---
apiVersion: v1
kind: Service
metadata:
  name: articles-service
  labels:
    app: articles-service
spec:
  selector:
    app: articles-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
