apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-service
  labels:
    app: jokes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jokes-service
  template:
    metadata:
      labels:
        app: jokes-service
    spec:
      containers:
      - name: jokes-service
        image: anurag2911/jokes-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: JokeConfig__MongoUri
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: connectionString
        - name: JokeConfig__NatsUrl
          value: "nats://nats.nats-system:4222"
        - name: JokeConfig__DatabaseName
          value: "newsdb"
        - name: JokeConfig__RefreshIntervalMinutes
          value: "60"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /jokes-api/stats
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: jokes-service
  labels:
    app: jokes-service
spec:
  selector:
    app: jokes-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
