apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-service
  labels:
    app: jokes-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jokes-service
  template:
    metadata:
      labels:
        app: jokes-service
    spec:
      containers:
      - name: jokes-service
        image: justscroll/jokes-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: jokes-db-secret
              key: CONNECTION_STRING
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
